# Configuration for GitHub repository

# Repository metadata
repository:
  # Description of the repository
  description: Hệ thống quản lý tiệm cắt tóc nam hiện đại với đặt lịch trực tuyến, quản lý thợ cắt tóc, dịch vụ, sản phẩm và đánh giá khách hàng.
  
  # Website URL
  website: https://barber-shop-demo.example.com
  
  # Topics for the repository
  topics:
    - laravel
    - php
    - barber-shop
    - appointment-booking
    - salon-management
    - bootstrap
    - mysql
    - responsive-design
    - admin-dashboard
    - user-management
    - email-verification
    - payment-processing
    - vietnamese

# Social preview settings
social_preview:
  # Use README.md as social preview
  use_readme_as_preview: true
